### ISSUE TITLE
Error: Must use import to load ES Module: ../t3-chat/src/server/wsServer.ts

### ISSUE THREAD

**Issue by d2vin** [TomDoesTech/t3-chat#1]
Error: Must use import to load ES Module: /Users/devinminnihan/code/t3-chat/src/server/wsServer.ts
Instead change the require of /t3-chat/src/env/server.mjs to a dynamic import() which is available in all CommonJS modules.

getting this error on the command yarn dev:ws

followed the tutorial. I got this error when running yarn dev:ws
also copied your package.json, and your tsconfig.server.json and got the same result

**Comment by d2vin** [comment]
changing the env import on db/client.ts to const env = dynamic(() => import("../../env/server.mjs")); solved my issue

**Comment by RowenTey** [comment]
didn't work for me, any latest workarounds?
